version: '3.7'
services:
 dynamodb-local:
   image: amazon/dynamodb-local:latest
   container_name: dynamodb-local
   environment:
      - ./Djava.library.path=./DynamoDBLocal_lib
   volumes:
      - ./data:/home/dynamodblocal/data
   ports:
    - "8000:8000"
   working_dir: /home/dynamodblocal
   command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "./data"]
